name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.4.4=py312hfc0e8ea_100
  - archspec=0.2.3=pyhd3eb1b0_0
  - boltons=23.0.0=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.4.26=py312h06a4308_0
  - cffi=1.16.0=py312h5eee18b_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - conda=24.11.3=py312h06a4308_0
  - conda-content-trust=0.2.0=py312h06a4308_1
  - conda-libmamba-solver=24.7.0=pyhd3eb1b0_0
  - conda-package-handling=2.3.0=py312h06a4308_0
  - conda-package-streaming=0.10.0=py312h06a4308_0
  - cryptography=42.0.5=py312hdda0065_1
  - distro=1.9.0=py312h06a4308_0
  - expat=2.6.2=h6a678d5_0
  - fmt=9.1.0=hdb19cb5_1
  - frozendict=2.4.2=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - jsonpatch=1.33=py312h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libarchive=3.6.2=hfab0078_4
  - libcurl=8.7.1=h251f7ec_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmamba=1.5.8=hfe524e5_2
  - libmambapy=1.5.8=py312h2dafd23_2
  - libnghttp2=1.57.0=h2d74bed_0
  - libsolv=0.7.24=he621ea3_1
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxml2=2.13.1=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - menuinst=2.1.2=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - packaging=24.1=py312h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pip=24.2=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - pluggy=1.0.0=py312h06a4308_1
  - prettytable=3.5.0=py312h06a4308_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h5eee18b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.4=h5148396_1
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py312h06a4308_0
  - ruamel.yaml=0.17.21=py312h5eee18b_0
  - setuptools=72.1.0=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tqdm=4.66.4=py312he106c6f_0
  - truststore=0.8.0=py312h06a4308_0
  - urllib3=2.2.2=py312h06a4308_0
  - wcwidth=0.2.13=py312h06a4308_0
  - wheel=0.43.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.22.0=py312h2c38b39_0
  - zstd=1.5.5=hc292b87_2
  - pip:
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - comm==0.2.2
      - debugpy==1.8.5
      - decorator==5.1.1
      - defusedxml==0.7.1
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - filelock==3.15.4
      - fqdn==1.5.1
      - fsspec==2024.6.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - ipykernel==6.29.5
      - ipython==8.27.0
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mpmath==1.3.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - notebook-shim==0.2.4
      - numpy==2.1.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - overrides==7.7.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.18.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - send2trash==1.8.3
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - torch==2.4.0
      - tornado==6.4.1
      - traitlets==5.14.3
      - triton==3.0.0
      - types-python-dateutil==2.9.0.20240821
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - uri-template==1.3.0
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
prefix: /home/ubuntu/miniconda3
